[package]
name = "bridge-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap.workspace = true
dotenv.workspace = true
tokio.workspace = true
ethers-core.workspace = true
near-primitives.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
omni-types.workspace = true
solana-client.workspace = true
solana-sdk.workspace = true
nep141-connector = { path = "../bridge-sdk/connectors/nep141-connector" }
eth-connector = { path = "../bridge-sdk/connectors/eth-connector" }
fast-bridge = { path = "../bridge-sdk/connectors/fast-bridge" }
omni-connector = { path = "../bridge-sdk/connectors/omni-connector" }
near-bridge-client = { path = "../bridge-sdk/bridge-clients/near-bridge-client" }
evm-bridge-client = { path = "../bridge-sdk/bridge-clients/evm-bridge-client" }
solana-bridge-client = { path = "../bridge-sdk/bridge-clients/solana-bridge-client" }
wormhole-bridge-client = { path = "../bridge-sdk/bridge-clients/wormhole-bridge-client" }
